# $target is generated by Rust, never interpolated command text.
$session = (Get-Process -Id $PID).SessionId
$sid = [Security.Principal.WindowsIdentity]::GetCurrent().User.Value
function Inventory { @(Get-CimInstance Win32_Process | Where-Object { $_.SessionId -eq $session }) }
function IsOwned($p) {
    try { (Invoke-CimMethod -InputObject $p -MethodName GetOwnerSid).Sid -eq $sid } catch { $false }
}
function IsRoot($p) {
    $p.ExecutablePath -ieq $target.path -and
    $p.CommandLine -notmatch '(?:^|\s)--type(?:=|\s)|(?:^|\s)app-server(?:\s|$)' -and (IsOwned $p)
}
function HasProfile($p) {
    $profile = Get-DesktopProfile $p.CommandLine
    $profile -and [IO.Path]::GetFullPath($profile) -ieq [IO.Path]::GetFullPath($target.userData)
}
function BindProcess($p) {
    $handle = Get-Process -Id $p.ProcessId -ErrorAction Stop
    $null = $handle.Handle
    if ($handle.HasExited -or $handle.Path -ine $p.ExecutablePath) { throw 'Process changed before operation' }
    # CIM timestamps are microsecond precision; process handles retain 100ns ticks.
    if ([Math]::Abs($handle.StartTime.ToUniversalTime().Ticks - $p.CreationDate.ToUniversalTime().Ticks) -gt 9) {
        throw 'Process generation changed before operation'
    }
    $handle
}
$all = Inventory
$protected = @([uint32]$PID)
if ($target.isolated) { $protected += @($target.protectedPids | ForEach-Object { [uint32]$_ }) }
$ancestor = [uint32]$PID
for ($i=0; $i -lt 64; $i++) {
    $p = $all | Where-Object { $_.ProcessId -eq $ancestor } | Select-Object -First 1
    if (!$p -or !$p.ParentProcessId -or $protected -contains [uint32]$p.ParentProcessId) { break }
    $ancestor = [uint32]$p.ParentProcessId
    $protected += $ancestor
}
if ($target.isolated) {
    $roots = @($all | Where-Object { $_.ProcessId -eq $target.pid })
    if ($roots.Count -ne 1 -or !(IsRoot $roots[0]) -or !(HasProfile $roots[0])) {
        throw 'Isolated desktop identity mismatch; production desktop was not touched'
    }
    $root = BindProcess $roots[0]
    if ($root.StartTime.ToUniversalTime().Ticks.ToString() -ne $target.started) {
        throw 'Isolated desktop manifest is stale'
    }
} else {
    # Never include explicitly isolated instances in normal discovery/restart.
    $roots = @($all | Where-Object { (IsRoot $_) -and !(Get-DesktopProfile $_.CommandLine) })
    if ($roots.Count -gt 1) { throw 'More than one desktop instance; restart manually' }
    $root = if ($roots.Count) { BindProcess $roots[0] } else { $null }
}
if ($root -and $protected -contains [uint32]$root.Id) {
    throw 'Refusing to restart the host that owns this operation'
}
if (!(Test-Path -LiteralPath $target.path -PathType Leaf)) { throw 'Launch executable is unavailable' }

$old = @()
$hadServer = $false
if ($root) {
    $ids = @([uint32]$root.Id)
    for ($i=0; $i -lt 32; $i++) {
        $children = @($all | Where-Object { $ids -contains [uint32]$_.ParentProcessId -and $ids -notcontains [uint32]$_.ProcessId } |
            ForEach-Object { [uint32]$_.ProcessId })
        if (!$children.Count) { break }
        $ids += $children
    }
    foreach ($p in $all | Where-Object { $ids -contains [uint32]$_.ProcessId }) {
        $server = $p.Name -match '^codex(?:[-_].*)?\.exe$' -and $p.CommandLine -match '(?:^|\s)app-server(?:\s|$)'
        if ($p.ExecutablePath -ine $target.path -and !$server) { continue }
        if ($p.CreationDate.ToUniversalTime() -lt $root.StartTime.ToUniversalTime().AddMilliseconds(-1)) {
            throw 'Descendant predates the selected desktop'
        }
        if (!(IsOwned $p) -or $protected -contains [uint32]$p.ProcessId) { throw 'Unsafe process scope' }
        $old += BindProcess $p
        if ($server) { $hadServer = $true }
    }
    if ($root.MainWindowHandle -ne 0 -and !$root.CloseMainWindow()) { throw 'Desktop refused to close' }
    $null = $root.WaitForExit(5000)
    $root.Refresh()
    if (!$root.HasExited -and $root.MainWindowHandle -ne 0) {
        throw 'Desktop still has a visible window or save prompt; finish work and quit manually'
    }
}
$forced = $false
# Close-to-tray is not exit. The UI warned the user to save before this action.
# Kill only retained, exact-generation application handles, never names or /T.
foreach ($p in $old) {
    if (!$p.HasExited) {
        try { $p.Kill(); $forced = $true }
        catch {
            # Windows can report access denied when a child exits between the
            # status check and TerminateProcess. Only accept a confirmed exit.
            if (!$p.WaitForExit(1500)) { throw "Cannot stop verified application PID $($p.Id)" }
        }
    }
}
foreach ($p in $old) {
    if (!$p.WaitForExit(8000)) { throw 'Old desktop/backend did not exit; not relaunching' }
}
if ($target.isolated) {
    $env:CODEX_HOME = $target.codexHome
    $env:CODEX_ELECTRON_USER_DATA_PATH = $target.userData
    $env:CODEX_CLI_PATH = $target.engine
    $arguments = @(('--user-data-dir="' + $target.userData + '"'), '--remote-debugging-address=127.0.0.1',
        ('--remote-debugging-port=' + $target.port))
    $launched = Start-Process -FilePath $target.path -ArgumentList $arguments -PassThru
} else {
    $launched = Start-Process -FilePath $target.path -PassThru
}
$deadline = [DateTime]::UtcNow.AddSeconds(15)
$manifestUpdated = $false
do {
    Start-Sleep -Milliseconds 350
    $launched.Refresh()
    if ($launched.HasExited) { throw 'New desktop exited before readiness' }
    $all = Inventory
    $new = $all | Where-Object { $_.ProcessId -eq $launched.Id } | Select-Object -First 1
    if (!$new -or !(IsRoot $new)) { continue }
    if ($target.isolated -and !(HasProfile $new)) { throw 'New desktop lost its isolated profile' }
    if ($target.isolated -and !$manifestUpdated) {
        $target.pid = $launched.Id
        $target.started = $launched.StartTime.ToUniversalTime().Ticks.ToString()
        $staging = $target.manifest + '.next'
        [IO.File]::WriteAllText($staging, ($target | ConvertTo-Json -Compress), [Text.UTF8Encoding]::new($false))
        [IO.File]::Replace($staging, $target.manifest, ($target.manifest + '.previous'))
        $manifestUpdated = $true
    }
    $ids = @([uint32]$new.ProcessId)
    for ($i=0; $i -lt 24; $i++) {
        $children = @($all | Where-Object { $ids -contains [uint32]$_.ParentProcessId -and $ids -notcontains [uint32]$_.ProcessId } |
            ForEach-Object { [uint32]$_.ProcessId })
        if (!$children.Count) { break }
        $ids += $children
    }
    $serverReady = @($all | Where-Object { $ids -contains [uint32]$_.ProcessId -and $_.CommandLine -match '(?:^|\s)app-server(?:\s|$)' }).Count -gt 0
    if ($launched.MainWindowHandle -ne 0 -and (!$hadServer -or $serverReady)) {
        if ($target.isolated) {
            $listener = @(Get-NetTCPConnection -State Listen -LocalPort $target.port -ErrorAction SilentlyContinue)
            if (!$listener.Count) { continue }
            if (@($listener | Where-Object { $ids -notcontains [uint32]$_.OwningProcess }).Count) {
                throw 'Debug listener ownership mismatch'
            }
        }
        @{ pid=$launched.Id; backendReady=$serverReady; forced=$forced; wasRunning=($null -ne $root) } |
            ConvertTo-Json -Compress
        exit 0
    }
} while ([DateTime]::UtcNow -lt $deadline)
throw 'No new visible desktop/backend within timeout; configuration remains saved'
